[build]
  command = "remix build"
  functions = "netlify/functions"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/zoopla/*"
  to = "https://www.zoopla.co.uk/:splat"
  status = 200

[[redirects]]
  from = "/rightmove/*"
  to = "https://www.rightmove.co.uk/:splat"
  status = 200

[[redirects]]
  from = "/onthemarket/*"
  to = "https://www.onthemarket.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
